### ISSUE TITLE
requirements.txt file?

### ISSUE THREAD

**Issue by bmabey** [brandomr/document_cluster#1] opened 2015-06-26 23:45 UTC
When trying to run the notebook I ran into the following error:

```

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-2-8a8f6d507950> in <module>()
     12 synopses_clean_wiki = []
     13 for text in synopses_wiki:
---> 14     text = nltk.clean_html(text)
     15     #strips html formatting
     16     text = text.replace('\xef', '')

/Users/bmabey/.virtualenvs/rbl-data/lib/python2.7/site-packages/nltk/util.pyc in clean_html(html)
    344 
    345 def clean_html(html):
--> 346     raise NotImplementedError ("To remove HTML markup, use BeautifulSoup's get_text() function")
    347 
    348 def clean_url(url):

NotImplementedError: To remove HTML markup, use BeautifulSoup's get_text() function
```

I'm guessing that I have a newer version of `nltk` installed. Could you push a `requirements.txt` file for this notebook so an appropriate virtual env can be created?

BTW, I was trying to run this notebook so I could use my new [pyLDAvis](https://github.com/bmabey/pyLDAvis) project to visualize the LDA model you create at the end.

**Comment by brandomr** [comment] 2015-06-27 00:06
@bmabey definitely will do. The error looks like NLTK is using BeautifulSoup so you might try

`pip install beautifulsoup4`

I'll run the notebook in a virtualenv and add a requirements.txt 

You're project looks great, no doubt I'll find use for it in the future.

**Comment by Fil** [comment] 2015-06-28 14:21
The problem is that nltk has now dropped the function `clean_html()`, see http://stackoverflow.com/questions/26002076/python-nltk-clean-html-not-implemented
This is solved in PR #2 which calls bs4

Also:
- I had to `pip install mpld3`
- I got a deprecation warning in the gensim/scipy part:

```
/Library/Python/2.7/site-packages/numpy-override/numpy/lib/utils.py:134: DeprecationWarning: `scipy.sparse.sparsetools` is deprecated!
scipy.sparse.sparsetools is a private module for scipy.sparse, and should not be used.
```

**Comment by brandomr** [comment] 2015-06-28 16:24
Thanks @fil and @bmabey I've merged the update.

**Comment by brandomr** [comment] 2015-06-28 16:28
@bmabey will add the requirements.txt today...reopened

**Comment by bmabey** [comment] 2015-06-28 17:08
I already added one but you may want to slim it down a bit. I just did a `pip freeze > requirements.txt` after I installed all the needed libs in a new env.

BTW, I played around with the corpus in pyLDAvis a bit here: http://nbviewer.ipython.org/github/bmabey/document_cluster/blob/pyldavis/cluster_analysis.ipynb#Visualizing-LDA-models

**Comment by brandomr** [comment] 2015-06-29 13:57
Got it, thanks @bmabey and thanks for sharing the notebook--very helpful and the project is looking great.

**Closed as completed by brandomr** 2015-06-29 13:57 UTC
